#!/bin/sh

dotfiles="$HOME/.dotfiles"

# Download dotfiles
if [ ! -e "$dotfiles" ]; then
  tmp=$(mktemp)
  curl -LsSo "$tmp" https://github.com/duailibe/dotfiles/tarball/main
  mkdir "$dotfiles"
  tar -xzf "$tmp" --directory "$dotfiles" --strip-components 1
fi

# Install Xcode CLI tools
if ! xcode-select --print-path &> /dev/null; then
  echo "Installing Xcode command line tools"
  xcode-select --install
fi

cd "$dotfiles" || exit

if [ ! -e "$dotfiles/.git" ]; then
  git init -q -b main
  git remote add origin "https://github.com/duailibe/dotfiles.git"
  git fetch -q origin
fi

make
