set background=dark
colorscheme one
" Allow italics for comments
"let g:one_allow_italics=1

filetype indent plugin on
syntax on

set softtabstop=2
set expandtab

" Show numbers
set number
set showcmd
set cursorline

set incsearch
set hlsearch
nnoremap <Leader><Space> :nohlsearch<CR>

set wildmenu
