tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"

brew "asdf"
brew "coreutils"
brew "fish"
brew "gh"
brew "git"
brew "grc"
brew "mas"
brew "postgresql"
brew "terminal-notifier"

# dependencies
brew "gnupg"
brew "openssl"
brew "readline"

# apps
cask "1password"
cask "dropbox"
cask "google-chrome"
cask "kap"
cask "font-fira-code"
cask "macpass"
cask "rectangle"
cask "rocket"
cask "slack"
cask "spotify"
cask "telegram"
cask "vlc"
cask "whatsapp"

mas "The Unarchiver", id: 425424353
